# Generated by Django 5.0.6 on 2024-09-07 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=40)),
                ('vehicle_type', models.CharField(choices=[('Bike', 'Bike'), ('Car', 'Car')], max_length=100)),
                ('driver_slug', models.SlugField(max_length=100, unique=True)),
                ('Driver_license', models.ImageField(upload_to='driver/license')),
                ('isApproved', models.BooleanField(default=False)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theuser', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thedriverprof', to='authentication.userprofile')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Driver',
            },
        ),
    ]
